// MACHINE GENERATED BY THE ABOVE COMMAND; DO NOT EDIT

// +build ignore

package diskio

// #include <windows.h>
// #include <winioctl.h>
import "C"

type DiskPerformance = C.DISK_PERFORMANCE

type DiskManagementControlCode uint32

const (
	IoctlDiskPerformance    DiskManagementControlCode = C.IOCTL_DISK_PERFORMANCE
	IoctlDiskPerformanceOff DiskManagementControlCode = C.IOCTL_DISK_PERFORMANCE_OFF
)
