// MACHINE GENERATED BY THE ABOVE COMMAND; DO NOT EDIT

// +build ignore

package diskio

// #include <windows.h>
// #include <winioctl.h>
import "C"

type DiskPerformance = C.DISK_PERFORMANCE

const (
	IoctlDiskPerformance    uint32 = C.IOCTL_DISK_PERFORMANCE
	IoctlDiskPerformanceOff uint32 = C.IOCTL_DISK_PERFORMANCE_OFF
)
